EXTERNAL get(key)
EXTERNAL get_str(key)
EXTERNAL set(key, value)
EXTERNAL increase(key, amount)
EXTERNAL add(target, item)
EXTERNAL remove(target, item)
EXTERNAL has(target, item)
EXTERNAL move(npc, location)
EXTERNAL shop(items)
EXTERNAL combat(enemy, hp, damage, on_win, on_lose, on_run)