EXTERNAL get(key)
EXTERNAL get_str(key)
EXTERNAL set(key, value)
EXTERNAL gain(key, amount)
EXTERNAL increase(key, amount)
EXTERNAL add_item(target, item)
EXTERNAL remove_item(target, item)
EXTERNAL has_item(target, item)
EXTERNAL move_npc(npc, location)
EXTERNAL shop(items)
EXTERNAL combat(enemy, hp, damage, on_win, on_lose, on_run)