from .factory import ContextFactory as ContextFactory
from context import Context as Context
from pathlib import Path
from typing import Any

NPC_KEYWORDS: set[str]

def load_yaml(path: Path) -> dict: ...

class World:
    rooms_dir: Path
    npcs_dir: Path
    items_dir: Path
    pc_file: Path
    flags_file: Path
    world_state: dict[str, Any]
    flags: dict[str, Any]
    rooms: dict[str, dict]
    items: dict[str, dict]
    npcs: dict[str, dict]
    visited: set[str]
    context_stack: list[Context]
    context_factory: ContextFactory
    current_room: str
    def __init__(self, game_path: Path) -> None: ...
    def load_world(self) -> None: ...
    def get_state(self, key): ...
    def set_state(self, key, value) -> None: ...
    def add_item(self, key, item) -> None: ...
    def npcs_in_room(self) -> list[str]: ...
    def display_room(self) -> None: ...
    def check_accost(self) -> str | None: ...
    def check_block(self, category, target) -> str | None: ...
    def get_actions(self) -> list[tuple[str, str]]: ...
    def handle_action(self, verb: str, target: str) -> None: ...
    def get_context(self) -> Context: ...
    def push_context(self, context: str, **kwargs) -> None: ...
    def pop_context(self, **kwargs) -> Context: ...
