from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from world import World


class Context:
    def actions(self, world: World) -> list[tuple[str, str]]: ...
    def apply(self, verb: str, target: str, world: World) -> None: ...
    def is_finished(self, world: World) -> bool: ...
    def on_enter(self, world: World) -> None: ...
    def on_resume(self, world: World, **kwargs) -> None: ...